line-length = 120
target-version = "py311"
exclude = [
    ".git",
    ".venv",
    "build",
    "dist",
]

[lint]
ignore = [
    "E501",
    "BLE001",
    "F401",
    "F841",
    "I001",
    "W293",
    "W291",
    "W292",
    "E722",
    "E402",
]
